### ISSUE TITLE
Request: open a "home" url upon launch?

### ISSUE THREAD

**Issue by FlyingVee313** [curzel-it/pipper#1]
Hi.  This is a very cool app.  I found it due to your post in a forum.  I'm not using it for the purpose most people would... do keep a video conferencing window on top, but rather I use pro audio recording software by a company called MOTU and their audio hardware uses a web browser to display the user interface that allows adjusting an internal DSP mixer as well as configuring internal routing of audio, etc.  So having this mixer float above my other apps, like recording software, is extremely useful.  By making a bookmark to access the audio hardware (it looks like this: http://localhost:1280/0001f2fffe014e3b/#mixing... I can launch Pipper, choose that bookmark, and have the mixer appear in a floating window that stays open over my recording program.

Anyway... it would be awesome if when I launch Pipper I could designate a URL that it opens upon launch.

Thanks so much for making this great app!

**Comment by curzel-it** [comment]
Hey, thanks for the feedback, and that is a cool use case indeed!
Some sort of "homepage" is actually need, I will add that later today, hang on!
Also, would you be able to provide an anonymised screenshot? I'd love to add this one to the gallery.

**Comment by curzel-it** [comment]
There you go, seems to be working fine! https://github.com/curzel-it/pipper/releases/tag/v1.0.2

**Comment by FlyingVee313** [comment]
Hi Federico!  I’m spreading the word on the forums and a board that I run for MOTU Digital Performer users… https://motunation.com <https://motunation.com/>

I made a YouTube video demonstrating how Pipper can be used for this purpose.  Not a screen shot, but maybe still useful.  I can make a screens shot if you like (downsized because I’m using a 4K monitor).

Here’s the video:

https://youtu.be/uZrAAGjKsAI <https://youtu.be/uZrAAGjKsAI>

Oh… and THANK YOU for adding the Home URL feature.  That makes this such a great tool!  I guess at some point you should start charging for it.

James Steele
https://www.jamessteeleproject.com <https://www.jamessteeleproject.com/>
http://www.facebook.com/jamessteeleproject <http://www.facebook.com/jamessteeleproject>
Admin @ http://motunation.com <http://motunation.com/>

**Comment by curzel-it** [comment]
Haha! Youtube video is even better, thanks a lot!
If you have any other feedback let me know :D

**Comment by FlyingVee313** [comment]
Thanks!  Only small thing I noticed is that when adding a bookmark, whatever is entered in the bookmark URL is also automatically duplicated in the icon URL field.

James Steele
https://www.jamessteeleproject.com <https://www.jamessteeleproject.com/>
http://www.facebook.com/jamessteeleproject <http://www.facebook.com/jamessteeleproject>
Admin @ http://motunation.com <http://motunation.com/>

**Comment by curzel-it** [comment]
Alright, will take a look at it soon then, thanks ;)
