### ISSUE TITLE
About dialog window should be not behind pipper

### ISSUE THREAD

**Issue by muescha** [curzel-it/pipper#11]
the about dialog window should be not behind pipper

![Bildschirmfoto 2023-11-23 um 00 48 06](https://github.com/curzel-it/pipper/assets/184316/5ccdf814-3443-4bd7-8d64-9d6f28d1b1ff)

**Comment by curzel-it** [comment]
Hi @muescha, thanks for all the feedback you shared today!
The "floating" effect is controlled by the `NSWindow.level` property, I need to check if there is an avaiable value there that allows to stay over other apps but below dialogs.
If there is on, happy to add it, if there isn't one I am afraid this will be very challenging to solve.
I should be able to check this during the weekend, I'll get back to you soon 👍

**Comment by muescha** [comment]
If it would behind **all** dialogs it would be nice.

The dialog I mentioned is the about dialog from pipper, which I expect to be above the pipper app.

**Comment by curzel-it** [comment]
So... I tried all available levels, and couldn't find one that works "good enough".
If this is blocking a specific use-case of yours, it might be worth for you to give it a shot, it's a single line of code:
```
self?.level = shouldHover ? .floating : .normal
```
Just relpace `floating` with any other available value.

Instead, if you've reported this as a possible improvement / cosmetic issue, thanks again, I really appreaciate it, but I don't think there's a valid solution that does not break other workflows :/

**Comment by muescha** [comment]
The positioning of Pipper's about dialog above Pipper seems purely cosmetic to me—an issue primarily related to appearance. I noticed that the settings dialog appears above Pipper and remains visible, whereas Pipper's about dialog appears behind Pipper.

To maintain consistency, perhaps displaying the about content within Pipper itself instead of introducing an additional about dialog could be a solution.

**Comment by curzel-it** [comment]
> I noticed that the settings dialog appears above Pipper and remains visible, whereas Pipper's about dialog appears behind Pipper.
Yes, this makes sense because this specific "about dialog" is something created and managed by macos, so it's a different process, the settings page is attached to the same window and therefore attaches properly.

> To maintain consistency, perhaps displaying the about content within Pipper itself instead of introducing an additional about dialog could be a solution.
Exactly. I have some plans for the menu bar, when I get to that I'll just replace the default dialog with something else 👍
