### ISSUE TITLE
It needs an appropriate app icon

### ISSUE THREAD

**Issue by craftzdog** [curzel-it/pipper#3]
Hi,

Thanks for creating such a useful app!
However, the current app icon does not represent its functionality or anything.
Would it be possible to have an appropriate app icon?
It feels strange every time I see it on the screen..

**Comment by craftzdog** [comment]
I don't know, but generated some ideas using midjourney:

![craftzdog_squared_with_round_edges_mobile_app_logo_design_flat__03ad918d-42a1-452d-ad74-5e3551764936](https://user-images.githubusercontent.com/1332805/222961055-907bf15f-fa75-4e2a-869d-983c0d6eb5a8.png)

![craftzdog_squared_with_round_edges_macos_app_logo_design_flat_v_e946d03d-d6ed-4fe4-b85c-c704f86a3774](https://user-images.githubusercontent.com/1332805/222961058-dabc55ea-59e5-497e-8b0b-b67d82b00a98.png)

Would you give me some keywords for generating better ones?

**Comment by curzel-it** [comment]
Hahaha! I actually did the same with dalle yesterday, but your results are clearly much better, ok, I'll send an update very soon!

**Comment by curzel-it** [comment]
I've settled on this... It's the icon for "Picture in Picture", which is what give the app it's name, I guess it makes sense...
It's not great, nor professional, but at least it's not a punch in the eye anymore haha
![512](https://user-images.githubusercontent.com/1446790/224259219-8098d868-620f-4014-98f4-b0c1959462b8.png)

**Comment by craftzdog** [comment]
Cool! Thanks for the update.
