### ISSUE TITLE
Hide title bar

### ISSUE THREAD

**Issue by curzel-it** [curzel-it/pipper#4]
Got a suggestion from an App Store review:
> I wanted to get a browser window to stay on top because I wanted to dock a twitch chat on top of everything else i was doing. This is perfect for those purposes. The only thing I could see making this better is an option to completely hide the menu bar making it slimmer.

Would be nice to have the title bar appear only appear while the mouse is hovering the view.

**Comment by dongphuchaitrieu** [comment]
Yes, I love having this feature!

**Comment by curzel-it** [comment]
![Screenshot 2023-11-04 at 09 13 03](https://github.com/curzel-it/pipper/assets/1446790/450285e8-fc44-41d3-b3ab-923a0dc9d78c)
![Screenshot 2023-11-04 at 09 13 08](https://github.com/curzel-it/pipper/assets/1446790/f2779638-5197-4476-a556-36faa74d579f)
Next week
