### ISSUE TITLE
Suggestion: Easier toggle for floating

### ISSUE THREAD

**Issue by tflo** [curzel-it/pipper#5]
I was looking for a shortcut to quickly enable/disable floating for a window, but couldn't find any.

Hence my suggestion: Move the Float setting ("Always on Top") to the Window menu. This would allow us to assign a shortcut via system. 

Thanks for considering, and thanks for the useful app! 

– Tom

**Comment by curzel-it** [comment]
This is actually a great suggestion, thanks for reaching out!
As a first step, I have added a toggle to the header, which you access via `Command + Shift + P`:
![Screenshot 2023-03-10 at 09 14 12](https://user-images.githubusercontent.com/1446790/224260516-6c0f75a4-26c3-4b9c-99e8-1f86745f8ce5.png)
![Screenshot 2023-03-10 at 09 14 17](https://user-images.githubusercontent.com/1446790/224260523-289e0b92-809c-47aa-889e-52460b9a4de1.png)

I'm looking into refactoring the header of the app, and that will be the occasion for having all settings in the menu bar, like:
![image](https://user-images.githubusercontent.com/1446790/224260862-8e9e41b7-d538-4443-a7ed-3dccc93212f9.png)

Feature is now available on main branch, will send to app store today
Cheers!
