### ISSUE TITLE
Pipper not working when apps are full screened - macOS

### ISSUE THREAD

**Issue by Fabian-AD** [curzel-it/pipper#6]
This is a great program and I use it every day! One thing I noticed is that in macOS the Pipper window does not show when other apps are fullscreened (or splitscreened with other apps) in new 'desktops'. Would be useful to have an option to have the Pipper window persist even when apps are fullscreened. Thanks anyways!

**Comment by curzel-it** [comment]
Hi @Fabian-AD, thanks for reaching out, it's actually very easy to implement, I think I will add another option, `Stay over all spaces`, it will be off by default.
Update should be coming in a few days!
<img width="890" alt="image" src="https://user-images.githubusercontent.com/1446790/227050612-b77ca164-4086-481c-9f10-322687b3df3e.png">
