### ISSUE TITLE
It seems not compatible with Sonoma 14.0

### ISSUE THREAD

**Issue by ocatteau** [curzel-it/pipper#7]
Hello !
First of all, thanks for this app that I really like !
I have upgraded my Mac OS to Sonoma 14.0. Nothing happens when I click on a bookmark button.  Is it a bug or a security problem ?
Thanks !

**Comment by douglaslassance** [comment]
I'm not wanting to add to the fire, but it also does not seem to persist across spaces.

**Comment by curzel-it** [comment]
Sorry for the wait @ocatteau, I actually released a fix several weeks ago, it should be good now 😀 

@douglaslassance yes, can confirm that unfortunately, I'll promise I'll fix it eventually 😅

**Comment by curzel-it** [comment]
@douglaslassance Should be fixed in 1.4!

**Comment by douglaslassance** [comment]
I got the update. It works great.
Thanks.
