### ISSUE TITLE
Scroll to adjust opacity?

### ISSUE THREAD

**Issue by javentous** [curzel-it/pipper#9]
Hey, thanks for the wonderful app, it's really useful. Let me know if there's a better place than Github Sponsor to send you coffee money.

I use an app called [Floating](https://apps.apple.com/ca/app/floating-picture-in-picture/id1508833245?mt=12), and it has a cool feature where I can scroll up or down to adjust opacity. If there was something similar in Pipper I think it would be really cool. Still a great app nonetheless. As well, when I adjust opacity on Pipper it looks a bit strange compared to Floating. I'll add some images so you get what I mean.

Thanks again for the work.

<img width="1205" alt="image" src="https://github.com/curzel-it/pipper/assets/12705383/8e48d886-771b-49da-97dc-920fc77f721f">

Left is Pipper, right is Floating. It seems it has something to do with the white background of YouTube? Not sure.

**Comment by javentous** [comment]
Yeah, seems to be due to the white background, here's another image after I changed the YouTube setting to dark.

<img width="1165" alt="image" src="https://github.com/curzel-it/pipper/assets/12705383/85ebd8eb-81b0-440d-a234-c1161b2e3c76">

**Comment by curzel-it** [comment]
Yes, can confirm this.
I'm thinking about allowing users to inject js and css, we can probably use that to remove backgrounds on "known websites" (such as YouTube).
Food for thought!
